import './globals.css'
import { Providers } from './providers'
import { getServerSession } from "next-auth";


export const metadata = {
  title: 'Quiz App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
