# Generated by Django 4.2.6 on 2023-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_address",
            field=models.EmailField(
                max_length=80, unique=True, verbose_name="Email Address"
            ),
        ),
    ]
