# Generated by Django 4.2.6 on 2023-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answerchoice",
            old_name="answer",
            new_name="option_1",
        ),
        migrations.RemoveField(
            model_name="answerchoice",
            name="is_correct_answer",
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        models.CharField(max_length=500),
                        models.CharField(max_length=500),
                    ),
                    (
                        models.CharField(max_length=500),
                        models.CharField(max_length=500),
                    ),
                    (
                        models.CharField(max_length=500),
                        models.CharField(max_length=500),
                    ),
                    (
                        models.CharField(max_length=500),
                        models.CharField(max_length=500),
                    ),
                ],
                max_length=125,
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="option_2",
            field=models.CharField(default="A", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="option_3",
            field=models.CharField(default="B", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="option_4",
            field=models.CharField(default="C", max_length=500),
            preserve_default=False,
        ),
    ]
