# Generated by Django 4.2.6 on 2023-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["email_address"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
