# Generated by Django 4.2.6 on 2023-10-26 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_customuser_options_alter_customuser_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
