import React from "react";
import Layout from "../components/layout/dashboard/Layout";

export const metadata = {
  title: "Quiz App - Dashboard",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <Layout/>
    </>
  );
}

export default page;
