import React from "react";
import Layout from "@/components/dashboard/Layout";
import Content from "@/components/dashboard/Content";

export const metadata = {
  title: "Quiz App - Dashboard",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <Layout>
        <Content />
      </Layout>
    </>
  );
}

export default page;
